# Generated by Django 5.2.6 on 2025-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name=1020)),
                ('last_name', models.CharField(verbose_name=1000)),
                ('email', models.CharField(verbose_name=2500)),
                ('phone', models.CharField(verbose_name=10)),
                ('address', models.CharField(verbose_name=200)),
                ('city', models.CharField(verbose_name=200)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
